# <center> Hands-on 1

Given a sample list, tuple and a set with elements as numbers from 1-10. Convert each
of the data types into a pandas series. Create a separate list of index values for the
series.

In [155]:
import pandas as pd

In [156]:
l = [2, 4, 6, 8, 10, 2, 4, 6, 8, 10]
t = (1, 3, 5, 7, 9, 1, 3, 5, 7, 9)
s = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [157]:
index_values = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [158]:
a = pd.Series(l, index=index_values)
a

A     2
B     4
C     6
D     8
E    10
F     2
G     4
H     6
I     8
J    10
dtype: int64

In [159]:
b = pd.Series(t, index=index_values)
b

A    1
B    3
C    5
D    7
E    9
F    1
G    3
H    5
I    7
J    9
dtype: int64

In [160]:
b = pd.Series(s, index=index_values)
b

TypeError: ignored

In [161]:
s={90,90.7,10,45,123}

In [162]:
s

{10, 45, 90, 90.7, 123}

In [163]:
l=[90,90.7,10,45,123]
l

[90, 90.7, 10, 45, 123]

2. Create a python dictionary with three key value pairs. Keep the keys as the first names,
and the respective last names as values in the dictionary. Use the dictionary to create a
pandas series.

In [164]:
import pandas as pd

name_dict = {
    'Ajay': 'Nagar',
    'Bhuvan ': 'Bam',
    'Ashish': 'Chanchlani'
}


name_series = pd.Series(name_dict)

print(name_series)

Ajay            Nagar
Bhuvan            Bam
Ashish     Chanchlani
dtype: object

3. Create a pandas series, with the elements as numbers from 1-10. Use the index values
starting from 0-10. For the above series:
- Convert it to a list.
- Convert it to a dictionary.
- Convert it to a tuple.
- Convert it to a set.

In [165]:
s = pd.Series(range(1,11))
s

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [166]:
list(s)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [167]:
s.tolist()

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [168]:
tuple(s)

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

In [169]:
dict(s)

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10}

In [170]:
set(s)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

4. Create a sample pandas series with x integer elements. Perform the following operations
on the same:
- Print the first 5 elements of the series
- Print the last 5 elements of the series
- Insert an integer value ‘50’ at the index 5.
- Update the last element in the series with the value 100.
- Delete the first element from the series.
Note: The index values must not be affected by the operations and should be uniform for
the series after the last operation.

In [171]:
a = pd.Series(range(1,11))
a

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [172]:
a[:5]

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [173]:
a[-5:]

5     6
6     7
7     8
8     9
9    10
dtype: int64

In [174]:
a=list(a)
a.insert(5,50)

In [175]:
a=pd.Series(a)

In [176]:
a

0      1
1      2
2      3
3      4
4      5
5     50
6      6
7      7
8      8
9      9
10    10
dtype: int64

In [177]:
a[10]=100

In [178]:
a

0       1
1       2
2       3
3       4
4       5
5      50
6       6
7       7
8       8
9       9
10    100
dtype: int64

In [179]:
a=a.drop(0)

In [180]:
a

1       2
2       3
3       4
4       5
5      50
6       6
7       7
8       8
9       9
10    100
dtype: int64

5. For a given pandas series obtained in the 4th step. Write a sample code to find the
element 100 in the series.

In [181]:
l = list(a)
for a in l :
    print(a==100)

False
False
False
False
False
False
False
False
False
True

In [182]:
for i in a:

  if i==100:
      print("Element 100 is present in the Series.")

TypeError: ignored

6. For the given series A and B, perform concatenation on the same.
- series_A = pd.Series([1,2,3,4,5])
- series_B = pd.Series([6,7,8,9,10])

In [183]:
series_A = pd.Series([1,2,3,4,5])
series_B = pd.Series([6,7,8,9,10])

In [184]:
pd.concat([series_A,series_B],ignore_index=True)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [185]:
series_A.append(series_B)

<ipython-input-185-e69a0a3b45e5>:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  series_A.append(series_B)

0     1
1     2
2     3
3     4
4     5
0     6
1     7
2     8
3     9
4    10
dtype: int64

In [186]:
concatenated_series = pd.concat([series_A, series_B])

print("Concatenated Series:")
print(concatenated_series)

Concatenated Series:
0     1
1     2
2     3
3     4
4     5
0     6
1     7
2     8
3     9
4    10
dtype: int64

7. Using loops in python, print all the elements within a pandas series.
Sample = pd.Series([1,2,3,4,5,6,7,8,9,10])

In [187]:
Sample = pd.Series([1,2,3,4,5,6,7,8,9,10])
for i in Sample:
    print(i)

1
2
3
4
5
6
7
8
9
10

8. For a given nested list and a sample dictionary, create two data frames using pandas.
List = [['AA','BB','CC'], ['DD','EE','FF'], ['GG','HH','II']]
Dictionary = { 'Kris': ['Jordan', 12,22],'Memphis': ['Depay', 23, 24]}

In [188]:
List = [['AA','BB','CC'], ['DD','EE','FF'], ['GG','HH','II']]
Dictionary = { 'Kris': ['Jordan', 12,22],'Memphis': ['Depay', 23, 24]}

df = pd.DataFrame(List,columns=['A','B',"C"])
df1 = pd.DataFrame(Dictionary)
df1

     Kris Memphis
0  Jordan   Depay
1      12      23
2      22      24

In [189]:
df

    A   B   C
0  AA  BB  CC
1  DD  EE  FF
2  GG  HH  II

9. Create a pandas Dataframe with two columns = [‘Name’, ‘Age’]. Perform the following
operations on the same.
- Print the first 3 rows of the Data Frame .
- Print the rows that have the age greater than 15.
- Insert 5 imaginary names and ages as values to the pandas Data Frame .
- Update the 5th row so that the name = john and age=56.
- Delete the first row from the Data Frame .

In [190]:
data=[['tom',10],['nick',20],['max',25],['rahul',30]]

In [191]:
df=pd.DataFrame(data, columns = ['Name', 'Age'])

In [192]:
df

    Name  Age
0    tom   10
1   nick   20
2    max   25
3  rahul   30

In [193]:
df.head(3)

   Name  Age
0   tom   10
1  nick   20
2   max   25

In [194]:
d={'Name':['sam','rahul','bob'],'Age':[10,15,30]}

In [195]:
df=df.append(pd.DataFrame(d),ignore_index=True)

<ipython-input-195-e0af5db27fab>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append(pd.DataFrame(d),ignore_index=True)

In [196]:
df

    Name  Age
0    tom   10
1   nick   20
2    max   25
3  rahul   30
4    sam   10
5  rahul   15
6    bob   30

In [197]:
df.loc[4,'Name']='John'
df.loc[4,'Age']=56

In [198]:
df

    Name  Age
0    tom   10
1   nick   20
2    max   25
3  rahul   30
4   John   56
5  rahul   15
6    bob   30

In [199]:
df.drop(0)

    Name  Age
1   nick   20
2    max   25
3  rahul   30
4   John   56
5  rahul   15
6    bob   30

In [200]:
df[df['Age']>15]

    Name  Age
1   nick   20
2    max   25
3  rahul   30
4   John   56
6    bob   30

10. For the Data Frame obtained from step 9, convert the same to a list and a dictionary
respectively.

In [201]:
df.to_dict()

{'Name': {0: 'tom',
  1: 'nick',
  2: 'max',
  3: 'rahul',
  4: 'John',
  5: 'rahul',
  6: 'bob'},
 'Age': {0: 10, 1: 20, 2: 25, 3: 30, 4: 56, 5: 15, 6: 30}}

In [202]:
df.values.tolist()

[['tom', 10],
 ['nick', 20],
 ['max', 25],
 ['rahul', 30],
 ['John', 56],
 ['rahul', 15],
 ['bob', 30]]

11. Create two separate Data Frame s A and B, and perform the following operations on
them.
- Concatenate the two Data Frame s to a new Data Frame C.
- Split the Data Frame C row wise.
- Split the Data Frame column wise based on a condition. For example - columns
values greater than 10, column values less than 10, etc.

In [203]:
data =  {'Name':['a','b','c','d','e'],'Age':[10,20,30,40,50]}
df = pd.DataFrame(data,index=[0,1,2,3,4])
df1 = pd.DataFrame(data={'Name':['f','g'],'Age':[60,70]})

In [204]:
df

  Name  Age
0    a   10
1    b   20
2    c   30
3    d   40
4    e   50

In [205]:
df1

  Name  Age
0    f   60
1    g   70

In [206]:
df_c = df.append(df1,ignore_index=True)

<ipython-input-206-0ef6b95bbad8>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_c = df.append(df1,ignore_index=True)

In [207]:
df_c

  Name  Age
0    a   10
1    b   20
2    c   30
3    d   40
4    e   50
5    f   60
6    g   70

In [208]:
df_c.iloc[:4,1:]

   Age
0   10
1   20
2   30
3   40

In [209]:
df[df['Age']>15]

  Name  Age
1    b   20
2    c   30
3    d   40
4    e   50

12. Create a Data Frame with columns Name and Age. Perform the following operations.
- Write a sample code to search for the Name/Names where Age is 20.
- Sort the Data Frame in ascending order of ages.
- Using Python loops, print the ages from the data frame and store it in a set.

In [210]:
df[df['Age']==20]

  Name  Age
1    b   20

In [211]:
df.sort_values(by='Age')

  Name  Age
0    a   10
1    b   20
2    c   30
3    d   40
4    e   50

In [212]:
ages_set = set()

for age in df['Age']:
    print(age)
    ages_set.add(age)

print("\nSet of Ages:", ages_set)

10
20
30
40
50

Set of Ages: {40, 10, 50, 20, 30}

## Hands-on 2

1. Load the dataset into the program using the pandas module and perform the following
operations.
- Print the first five rows of the dataset.
- Print the last five rows of the dataset.
- Print the column names from the dataset.
- Print the shape of the dataset.
- Print the information of the dataset with respect to each column in the data.
- Print the count of distinct values in each of the columns in the data.
- Check the dimensions and size of the data.
- Check for duplicate entries in each column.

In [213]:
a=pd.read_csv("cars (3).csv")
a.head()

    mpg   cylinders  cubicinches   hp  weightlbs   time-to-60   year     brand
0  14.0           8          350  165       4209           12   1972       US.
1  31.9           4           89   71       1925           14   1980   Europe.
2  17.0           8          302  140       3449           11   1971       US.
3  15.0           8          400  150       3761           10   1971       US.
4  30.5           4           98   63       2051           17   1978       US.

In [214]:
a[' weightlbs'].unique()

array(['4209', '1925', '3449', '3761', '2051', '3900', '4363', '4312',
       '3530', '2050', '2245', '2188', '4141', '3664', ' ', '4360',
       '2020', '3433', '2278', '2430', '2019', '2600', '3012', '4054',
       '1968', '1795', '1773', '4657', '3574', '2380', '2130', '3278',
       '2506', '1985', '3415', '1835', '2720', '3955', '3265', '3897',
       '4638', '3645', '3520', '3086', '2635', '3755', '2395', '1940',
       '3060', '4464', '3190', '3609', '2158', '4380', '4278', '2930',
       '2075', '1937', '3821', '2945', '2379', '2910', '2110', '4237',
       '3525', '1950', '1965', '1825', '3880', '3102', '2640', '2288',
       '2545', '2219', '3015', '3085', '2515', '2265', '2350', '4325',
       '4952', '3425', '2694', '2220', '1613', '2774', '3465', '2125',
       '1975', '2300', '4100', '3329', '2255', '3907', '4499', '3139',
       '3830', '3781', '4997', '4906', '2126', '2200', '2335', '2065',
       '2671', '3504', '2279', '2933', '4335', '3785', '2740', '3039',
       '2045', '4341', '2202', '1963', '4668', '2745', '1834', '2565',
       '4654', '2230', '2582', '1800', '2678', '4951', '3672', '4440',
       '4190', '1955', '3169', '2979', '2700', '2171', '2665', '1760',
       '3605', '2957', '3360', '2735', '3693', '3205', '2542', '2560',
       '4425', '3158', '2464', '3302', '2124', '2135', '2634', '3410',
       '3003', '4080', '2984', '2904', '2254', '3365', '3439', '2585',
       '2807', '2290', '2830', '2575', '2226', '2189', '4385', '3570',
       '2990', '2145', '4215', '3436', '3070', '3459', '3940', '4129',
       '4735', '2620', '2670', '4422', '4082', '4077', '2144', '2490',
       '1945', '2246', '2639', '3420', '3630', '2401', '3850', '3021',
       '4098', '2900', '2815', '3445', '1755', '2074', '3233', '2615',
       '2595', '4295', '3193', '2795', '4457', '3820', '4042', '2003',
       '4615', '1649', '2587', '2790', '3563', '2625', '2592', '4498',
       '3150', '4096', '2965', '1875', '4055', '3121', '4220', '2672',
       '4354', '3399', '3735', '2085', '2155', '2525', '2120', '2660',
       '2950', '3988', '2725', '2372', '3840', '2835', '3288', '3353'],
      dtype=object)

In [215]:
a.head()

    mpg   cylinders  cubicinches   hp  weightlbs   time-to-60   year     brand
0  14.0           8          350  165       4209           12   1972       US.
1  31.9           4           89   71       1925           14   1980   Europe.
2  17.0           8          302  140       3449           11   1971       US.
3  15.0           8          400  150       3761           10   1971       US.
4  30.5           4           98   63       2051           17   1978       US.

In [216]:
a.tail()

,mpg,cylinders,cubicinches,hp,weightlbs,time-to-60,year,brand
256,17.0,8,305,130,3840,15,1980,US.
257,36.1,4,91,60,1800,16,1979,Japan.
258,22.0,6,232,112,2835,15,1983,US.
259,18.0,6,232,100,3288,16,1972,US.
260,22.0,6,250,105,3353,15,1977,US.

In [217]:
a.columns

Index(['mpg', ' cylinders', ' cubicinches', ' hp', ' weightlbs', ' time-to-60',
       ' year', ' brand'],
      dtype='object')

In [218]:
a.shape

(261, 8)

In [219]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261 entries, 0 to 260
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           261 non-null    float64
 1    cylinders    261 non-null    int64
 2    cubicinches  261 non-null    object
 3    hp           261 non-null    int64
 4    weightlbs    261 non-null    object
 5    time-to-60   261 non-null    int64
 6    year         261 non-null    int64
 7    brand        261 non-null    object
dtypes: float64(1), int64(4), object(3)
memory usage: 16.4+ KB

In [220]:
a.nunique()

mpg             103
 cylinders        5
 cubicinches     75
 hp              85
 weightlbs      240
 time-to-60      17
 year            13
 brand            3
dtype: int64

In [221]:
a.ndim

2

In [222]:
a.duplicated().sum()

0

2. Check for null values in the dataset, and if found any replace the null values with 0.

In [223]:
a.isnull().sum()

mpg             0
 cylinders      0
 cubicinches    0
 hp             0
 weightlbs      0
 time-to-60     0
 year           0
 brand          0
dtype: int64

In [224]:
a.replace(' ',0,inplace=True)

In [225]:
a.isnull().sum()

mpg             0
 cylinders      0
 cubicinches    0
 hp             0
 weightlbs      0
 time-to-60     0
 year           0
 brand          0
dtype: int64

3. Describe the data based on parameters like mean, average, standard deviation, etc for
each of the columns.

In [226]:
a.describe()

              mpg   cylinders          hp   time-to-60         year
count  261.000000  261.000000  261.000000   261.000000   261.000000
mean    23.144828    5.590038  106.360153    15.547893  1976.819923
std      7.823570    1.733310   40.499959     2.910625     3.637696
min     10.000000    3.000000   46.000000     8.000000  1971.000000
25%     16.900000    4.000000   75.000000    14.000000  1974.000000
50%     22.000000    6.000000   95.000000    16.000000  1977.000000
75%     28.800000    8.000000  138.000000    17.000000  1980.000000
max     46.600000    8.000000  230.000000    25.000000  1983.000000

4. Calculate the correlation coefficient between each of the columns in the dataset.

In [227]:
a.corr()

<ipython-input-227-210c353a220b>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  a.corr()

                  mpg   cylinders        hp   time-to-60      year
mpg          1.000000   -0.776710 -0.774905     0.509070  0.550441
 cylinders  -0.776710    1.000000  0.845155    -0.578161 -0.322239
 hp         -0.774905    0.845155  1.000000    -0.744873 -0.383869
 time-to-60  0.509070   -0.578161 -0.744873     1.000000  0.312311
 year        0.550441   -0.322239 -0.383869     0.312311  1.000000

5. Create separate dataframes with respect to each distinct value in the brand column,
where the time-to-60 is less than 10.0.

In [228]:
a[(a[" brand"] == " US.") & (a[' time-to-60'] < 10)]

      mpg   cylinders  cubicinches   hp  weightlbs   time-to-60   year  brand
7    14.0           8          440  215       4312            9   1971    US.
52   14.0           8          340  160       3609            8   1971    US.
205  15.0           8          390  190       3850            9   1971    US.
244  14.0           8          454  220       4354            9   1971    US.

In [229]:
a[(a[" brand"] == " Europe.") & (a[' time-to-60'] < 10)]

Empty DataFrame
Columns: [mpg,  cylinders,  cubicinches,  hp,  weightlbs,  time-to-60,  year,  brand]
Index: []

In [230]:
a[(a[" brand"] == " Japan.") & (a[' time-to-60'] < 10)]

Empty DataFrame
Columns: [mpg,  cylinders,  cubicinches,  hp,  weightlbs,  time-to-60,  year,  brand]
Index: []

6. Create a separate data frame for cars whose hp is greater than 200 and time-to-60 is
less than 15.0

In [231]:
a[(a[' hp']>200)&(a[' time-to-60']<15)]

      mpg   cylinders  cubicinches   hp  weightlbs   time-to-60   year  brand
7    14.0           8          440  215       4312            9   1971    US.
44   14.0           8          455  225       3086           10   1971    US.
55   16.0           8          400  230       4278           10   1974    US.
132  12.0           8          455  225       4951           11   1974    US.
152  14.0           8          455  225       4425           10   1971    US.
189  13.0           8          440  215       4735           11   1974    US.
226  10.0           8          360  215       4615           14   1971    US.
244  14.0           8          454  220       4354            9   1971    US.

7. Create two separate data frames where in the first dataframe you sort the entire dataset
in descending order of hp, and in the second dataframe, you sort the entire dataset in
ascending order with respect to time-to-60.

In [232]:
a.sort_values(by=' time-to-60')

,mpg,cylinders,cubicinches,hp,weightlbs,time-to-60,year,brand
52,14.0,8,340,160,3609,8,1971,US.
7,14.0,8,440,215,4312,9,1971,US.
244,14.0,8,454,220,4354,9,1971,US.
205,15.0,8,390,190,3850,9,1971,US.
119,15.0,8,429,198,4341,10,1971,US.
...,...,...,...,...,...,...,...,...
202,23.9,8,260,90,3420,22,1980,US.
106,43.4,4,90,48,2335,24,1981,Europe.
164,23.0,4,97,54,2254,24,1973,Europe.
235,44.0,4,97,52,2130,25,1983,Europe.
51,27.2,4,141,71,3190,25,1980,Europe.

In [234]:
a.sort_values(by=' hp',ascending=False)

,mpg,cylinders,cubicinches,hp,weightlbs,time-to-60,year,brand
55,16.0,8,400,230,4278,10,1974,US.
152,14.0,8,455,225,4425,10,1971,US.
44,14.0,8,455,225,3086,10,1971,US.
132,12.0,8,455,225,4951,11,1974,US.
244,14.0,8,454,220,4354,9,1971,US.
...,...,...,...,...,...,...,...,...
247,44.3,4,90,48,2085,22,1981,Europe.
197,43.1,4,90,48,1985,22,1979,Europe.
106,43.4,4,90,48,2335,24,1981,Europe.
66,26.0,4,97,46,1950,21,1974,Europe.
36,26.0,4,97,46,1835,21,1971,Europe.

8. Create a dataframe, in order of top 10 heaviest cars in the cars data. Repeat the same
for top 10 lightest cars.

In [236]:
a[' weightlbs']=a[' weightlbs'].astype(int)
carheavy=a.sort_values(by=' weightlbs',ascending=False).head(10)
carheavy

      mpg   cylinders  cubicinches   hp   weightlbs   time-to-60   year  brand
100  11.0           8          400  150        4997           14   1974    US.
81   12.0           8          429  198        4952           12   1974    US.
132  12.0           8          455  225        4951           11   1974    US.
101  12.0           8          400  167        4906           13   1974    US.
189  13.0           8          440  215        4735           11   1974    US.
122  16.0           8          400  170        4668           12   1976    US.
27   14.0           8          351  148        4657           14   1976    US.
126  13.0           8          360  170        4654           13   1974    US.
41   14.0           8          302  140        4638           16   1975    US.
226  10.0           8          360  215        4615           14   1971    US.

In [237]:
a[' weightlbs']=a[' weightlbs'].astype(int)
carlow=a.sort_values(by=' weightlbs').head(10)
carlow

,mpg,cylinders,cubicinches,hp,weightlbs,time-to-60,year,brand
33,21.0,6,199,90,0,15,1971,US.
172,29.0,4,68,49,0,20,1974,Europe.
14,19.1,6,225,90,0,19,1981,US.
85,35.0,4,72,69,1613,18,1972,Japan.
227,31.0,4,76,52,1649,17,1975,Japan.
212,39.1,4,79,58,1755,17,1982,Japan.
143,35.1,4,81,60,1760,16,1982,Japan.
26,31.0,4,71,65,1773,19,1972,Japan.
25,33.0,4,91,53,1795,17,1977,Japan.
113,33.0,4,91,53,1795,18,1976,Japan.

9. Create separate dataframes with sorted values with respect to mpg in ascending and
descending order.

In [239]:
a.sort_values(by='mpg',ascending=False)

,mpg,cylinders,cubicinches,hp,weightlbs,time-to-60,year,brand
63,46.6,4,86,65,2110,18,1981,Japan.
247,44.3,4,90,48,2085,22,1981,Europe.
235,44.0,4,97,52,2130,25,1983,Europe.
106,43.4,4,90,48,2335,24,1981,Europe.
197,43.1,4,90,48,1985,22,1979,Europe.
...,...,...,...,...,...,...,...,...
101,12.0,8,400,167,4906,13,1974,US.
132,12.0,8,455,225,4951,11,1974,US.
13,11.0,8,350,180,3664,11,1974,US.
100,11.0,8,400,150,4997,14,1974,US.
226,10.0,8,360,215,4615,14,1971,US.

In [240]:
a.sort_values(by='mpg')

,mpg,cylinders,cubicinches,hp,weightlbs,time-to-60,year,brand
226,10.0,8,360,215,4615,14,1971,US.
13,11.0,8,350,180,3664,11,1974,US.
100,11.0,8,400,150,4997,14,1974,US.
81,12.0,8,429,198,4952,12,1974,US.
96,12.0,8,350,180,4499,13,1974,US.
...,...,...,...,...,...,...,...,...
197,43.1,4,90,48,1985,22,1979,Europe.
106,43.4,4,90,48,2335,24,1981,Europe.
235,44.0,4,97,52,2130,25,1983,Europe.
247,44.3,4,90,48,2085,22,1981,Europe.
63,46.6,4,86,65,2110,18,1981,Japan.

10. Split the dataset into two with respect to cars built before 2000, and after 2000.

In [241]:
a[a[' year']>2000]

Empty DataFrame
Columns: [mpg,  cylinders,  cubicinches,  hp,  weightlbs,  time-to-60,  year,  brand]
Index: []

In [242]:
a[a[' year']<2000]

,mpg,cylinders,cubicinches,hp,weightlbs,time-to-60,year,brand
0,14.0,8,350,165,4209,12,1972,US.
1,31.9,4,89,71,1925,14,1980,Europe.
2,17.0,8,302,140,3449,11,1971,US.
3,15.0,8,400,150,3761,10,1971,US.
4,30.5,4,98,63,2051,17,1978,US.
...,...,...,...,...,...,...,...,...
256,17.0,8,305,130,3840,15,1980,US.
257,36.1,4,91,60,1800,16,1979,Japan.
258,22.0,6,232,112,2835,15,1983,US.
259,18.0,6,232,100,3288,16,1972,US.
260,22.0,6,250,105,3353,15,1977,US.